language: java
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - export JAVA_HOME=$(/usr/libexec/java_home)
  - echo $JAVA_HOME
  - wget hughperkins.com/download/jeigen-1.2beta/Jeigen-onefat.jar
  - wget http://hughperkins.com/jeigen/jna-4.1.0.jar

script:
  - java -cp Jeigen-onefat.jar:jna-4.1.0.jar jeigen.TestSimple

notifications:
  email:
    on_success: never
    on_failure: never

